[TwitchEmoteID0]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID0

[TwitchEmoteX0]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX0

[TwitchEmoteY0]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY0

[TwitchEmoteImage0]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID0].png
X=[TwitchEmoteX0]
Y=(55 + [TwitchEmoteY0])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID1]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID1

[TwitchEmoteX1]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX1

[TwitchEmoteY1]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY1

[TwitchEmoteImage1]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID1].png
X=[TwitchEmoteX1]
Y=(55 + [TwitchEmoteY1])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID2]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID2

[TwitchEmoteX2]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX2

[TwitchEmoteY2]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY2

[TwitchEmoteImage2]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID2].png
X=[TwitchEmoteX2]
Y=(55 + [TwitchEmoteY2])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID3]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID3

[TwitchEmoteX3]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX3

[TwitchEmoteY3]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY3

[TwitchEmoteImage3]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID3].png
X=[TwitchEmoteX3]
Y=(55 + [TwitchEmoteY3])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID4]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID4

[TwitchEmoteX4]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX4

[TwitchEmoteY4]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY4

[TwitchEmoteImage4]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID4].png
X=[TwitchEmoteX4]
Y=(55 + [TwitchEmoteY4])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID5]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID5

[TwitchEmoteX5]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX5

[TwitchEmoteY5]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY5

[TwitchEmoteImage5]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID5].png
X=[TwitchEmoteX5]
Y=(55 + [TwitchEmoteY5])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID6]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID6

[TwitchEmoteX6]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX6

[TwitchEmoteY6]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY6

[TwitchEmoteImage6]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID6].png
X=[TwitchEmoteX6]
Y=(55 + [TwitchEmoteY6])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID7]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID7

[TwitchEmoteX7]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX7

[TwitchEmoteY7]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY7

[TwitchEmoteImage7]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID7].png
X=[TwitchEmoteX7]
Y=(55 + [TwitchEmoteY7])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID8]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID8

[TwitchEmoteX8]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX8

[TwitchEmoteY8]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY8

[TwitchEmoteImage8]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID8].png
X=[TwitchEmoteX8]
Y=(55 + [TwitchEmoteY8])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID9]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID9

[TwitchEmoteX9]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX9

[TwitchEmoteY9]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY9

[TwitchEmoteImage9]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID9].png
X=[TwitchEmoteX9]
Y=(55 + [TwitchEmoteY9])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID10]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID10

[TwitchEmoteX10]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX10

[TwitchEmoteY10]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY10

[TwitchEmoteImage10]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID10].png
X=[TwitchEmoteX10]
Y=(55 + [TwitchEmoteY10])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID11]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID11

[TwitchEmoteX11]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX11

[TwitchEmoteY11]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY11

[TwitchEmoteImage11]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID11].png
X=[TwitchEmoteX11]
Y=(55 + [TwitchEmoteY11])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID12]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID12

[TwitchEmoteX12]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX12

[TwitchEmoteY12]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY12

[TwitchEmoteImage12]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID12].png
X=[TwitchEmoteX12]
Y=(55 + [TwitchEmoteY12])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID13]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID13

[TwitchEmoteX13]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX13

[TwitchEmoteY13]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY13

[TwitchEmoteImage13]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID13].png
X=[TwitchEmoteX13]
Y=(55 + [TwitchEmoteY13])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID14]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID14

[TwitchEmoteX14]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX14

[TwitchEmoteY14]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY14

[TwitchEmoteImage14]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID14].png
X=[TwitchEmoteX14]
Y=(55 + [TwitchEmoteY14])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID15]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID15

[TwitchEmoteX15]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX15

[TwitchEmoteY15]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY15

[TwitchEmoteImage15]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID15].png
X=[TwitchEmoteX15]
Y=(55 + [TwitchEmoteY15])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID16]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID16

[TwitchEmoteX16]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX16

[TwitchEmoteY16]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY16

[TwitchEmoteImage16]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID16].png
X=[TwitchEmoteX16]
Y=(55 + [TwitchEmoteY16])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID17]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID17

[TwitchEmoteX17]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX17

[TwitchEmoteY17]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY17

[TwitchEmoteImage17]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID17].png
X=[TwitchEmoteX17]
Y=(55 + [TwitchEmoteY17])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID18]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID18

[TwitchEmoteX18]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX18

[TwitchEmoteY18]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY18

[TwitchEmoteImage18]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID18].png
X=[TwitchEmoteX18]
Y=(55 + [TwitchEmoteY18])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID19]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID19

[TwitchEmoteX19]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX19

[TwitchEmoteY19]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY19

[TwitchEmoteImage19]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID19].png
X=[TwitchEmoteX19]
Y=(55 + [TwitchEmoteY19])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID20]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID20

[TwitchEmoteX20]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX20

[TwitchEmoteY20]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY20

[TwitchEmoteImage20]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID20].png
X=[TwitchEmoteX20]
Y=(55 + [TwitchEmoteY20])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID21]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID21

[TwitchEmoteX21]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX21

[TwitchEmoteY21]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY21

[TwitchEmoteImage21]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID21].png
X=[TwitchEmoteX21]
Y=(55 + [TwitchEmoteY21])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID22]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID22

[TwitchEmoteX22]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX22

[TwitchEmoteY22]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY22

[TwitchEmoteImage22]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID22].png
X=[TwitchEmoteX22]
Y=(55 + [TwitchEmoteY22])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID23]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID23

[TwitchEmoteX23]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX23

[TwitchEmoteY23]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY23

[TwitchEmoteImage23]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID23].png
X=[TwitchEmoteX23]
Y=(55 + [TwitchEmoteY23])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID24]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID24

[TwitchEmoteX24]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX24

[TwitchEmoteY24]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY24

[TwitchEmoteImage24]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID24].png
X=[TwitchEmoteX24]
Y=(55 + [TwitchEmoteY24])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID25]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID25

[TwitchEmoteX25]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX25

[TwitchEmoteY25]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY25

[TwitchEmoteImage25]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID25].png
X=[TwitchEmoteX25]
Y=(55 + [TwitchEmoteY25])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID26]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID26

[TwitchEmoteX26]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX26

[TwitchEmoteY26]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY26

[TwitchEmoteImage26]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID26].png
X=[TwitchEmoteX26]
Y=(55 + [TwitchEmoteY26])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID27]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID27

[TwitchEmoteX27]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX27

[TwitchEmoteY27]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY27

[TwitchEmoteImage27]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID27].png
X=[TwitchEmoteX27]
Y=(55 + [TwitchEmoteY27])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID28]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID28

[TwitchEmoteX28]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX28

[TwitchEmoteY28]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY28

[TwitchEmoteImage28]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID28].png
X=[TwitchEmoteX28]
Y=(55 + [TwitchEmoteY28])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID29]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID29

[TwitchEmoteX29]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX29

[TwitchEmoteY29]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY29

[TwitchEmoteImage29]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID29].png
X=[TwitchEmoteX29]
Y=(55 + [TwitchEmoteY29])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID30]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID30

[TwitchEmoteX30]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX30

[TwitchEmoteY30]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY30

[TwitchEmoteImage30]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID30].png
X=[TwitchEmoteX30]
Y=(55 + [TwitchEmoteY30])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID31]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID31

[TwitchEmoteX31]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX31

[TwitchEmoteY31]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY31

[TwitchEmoteImage31]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID31].png
X=[TwitchEmoteX31]
Y=(55 + [TwitchEmoteY31])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID32]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID32

[TwitchEmoteX32]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX32

[TwitchEmoteY32]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY32

[TwitchEmoteImage32]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID32].png
X=[TwitchEmoteX32]
Y=(55 + [TwitchEmoteY32])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID33]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID33

[TwitchEmoteX33]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX33

[TwitchEmoteY33]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY33

[TwitchEmoteImage33]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID33].png
X=[TwitchEmoteX33]
Y=(55 + [TwitchEmoteY33])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID34]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID34

[TwitchEmoteX34]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX34

[TwitchEmoteY34]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY34

[TwitchEmoteImage34]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID34].png
X=[TwitchEmoteX34]
Y=(55 + [TwitchEmoteY34])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID35]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID35

[TwitchEmoteX35]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX35

[TwitchEmoteY35]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY35

[TwitchEmoteImage35]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID35].png
X=[TwitchEmoteX35]
Y=(55 + [TwitchEmoteY35])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID36]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID36

[TwitchEmoteX36]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX36

[TwitchEmoteY36]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY36

[TwitchEmoteImage36]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID36].png
X=[TwitchEmoteX36]
Y=(55 + [TwitchEmoteY36])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID37]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID37

[TwitchEmoteX37]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX37

[TwitchEmoteY37]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY37

[TwitchEmoteImage37]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID37].png
X=[TwitchEmoteX37]
Y=(55 + [TwitchEmoteY37])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID38]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID38

[TwitchEmoteX38]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX38

[TwitchEmoteY38]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY38

[TwitchEmoteImage38]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID38].png
X=[TwitchEmoteX38]
Y=(55 + [TwitchEmoteY38])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID39]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID39

[TwitchEmoteX39]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX39

[TwitchEmoteY39]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY39

[TwitchEmoteImage39]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID39].png
X=[TwitchEmoteX39]
Y=(55 + [TwitchEmoteY39])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID40]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID40

[TwitchEmoteX40]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX40

[TwitchEmoteY40]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY40

[TwitchEmoteImage40]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID40].png
X=[TwitchEmoteX40]
Y=(55 + [TwitchEmoteY40])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID41]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID41

[TwitchEmoteX41]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX41

[TwitchEmoteY41]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY41

[TwitchEmoteImage41]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID41].png
X=[TwitchEmoteX41]
Y=(55 + [TwitchEmoteY41])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID42]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID42

[TwitchEmoteX42]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX42

[TwitchEmoteY42]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY42

[TwitchEmoteImage42]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID42].png
X=[TwitchEmoteX42]
Y=(55 + [TwitchEmoteY42])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID43]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID43

[TwitchEmoteX43]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX43

[TwitchEmoteY43]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY43

[TwitchEmoteImage43]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID43].png
X=[TwitchEmoteX43]
Y=(55 + [TwitchEmoteY43])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID44]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID44

[TwitchEmoteX44]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX44

[TwitchEmoteY44]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY44

[TwitchEmoteImage44]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID44].png
X=[TwitchEmoteX44]
Y=(55 + [TwitchEmoteY44])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID45]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID45

[TwitchEmoteX45]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX45

[TwitchEmoteY45]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY45

[TwitchEmoteImage45]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID45].png
X=[TwitchEmoteX45]
Y=(55 + [TwitchEmoteY45])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID46]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID46

[TwitchEmoteX46]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX46

[TwitchEmoteY46]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY46

[TwitchEmoteImage46]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID46].png
X=[TwitchEmoteX46]
Y=(55 + [TwitchEmoteY46])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID47]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID47

[TwitchEmoteX47]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX47

[TwitchEmoteY47]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY47

[TwitchEmoteImage47]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID47].png
X=[TwitchEmoteX47]
Y=(55 + [TwitchEmoteY47])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID48]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID48

[TwitchEmoteX48]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX48

[TwitchEmoteY48]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY48

[TwitchEmoteImage48]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID48].png
X=[TwitchEmoteX48]
Y=(55 + [TwitchEmoteY48])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID49]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID49

[TwitchEmoteX49]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX49

[TwitchEmoteY49]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY49

[TwitchEmoteImage49]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID49].png
X=[TwitchEmoteX49]
Y=(55 + [TwitchEmoteY49])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID50]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID50

[TwitchEmoteX50]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX50

[TwitchEmoteY50]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY50

[TwitchEmoteImage50]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID50].png
X=[TwitchEmoteX50]
Y=(55 + [TwitchEmoteY50])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID51]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID51

[TwitchEmoteX51]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX51

[TwitchEmoteY51]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY51

[TwitchEmoteImage51]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID51].png
X=[TwitchEmoteX51]
Y=(55 + [TwitchEmoteY51])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID52]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID52

[TwitchEmoteX52]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX52

[TwitchEmoteY52]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY52

[TwitchEmoteImage52]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID52].png
X=[TwitchEmoteX52]
Y=(55 + [TwitchEmoteY52])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID53]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID53

[TwitchEmoteX53]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX53

[TwitchEmoteY53]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY53

[TwitchEmoteImage53]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID53].png
X=[TwitchEmoteX53]
Y=(55 + [TwitchEmoteY53])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID54]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID54

[TwitchEmoteX54]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX54

[TwitchEmoteY54]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY54

[TwitchEmoteImage54]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID54].png
X=[TwitchEmoteX54]
Y=(55 + [TwitchEmoteY54])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID55]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID55

[TwitchEmoteX55]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX55

[TwitchEmoteY55]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY55

[TwitchEmoteImage55]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID55].png
X=[TwitchEmoteX55]
Y=(55 + [TwitchEmoteY55])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID56]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID56

[TwitchEmoteX56]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX56

[TwitchEmoteY56]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY56

[TwitchEmoteImage56]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID56].png
X=[TwitchEmoteX56]
Y=(55 + [TwitchEmoteY56])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID57]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID57

[TwitchEmoteX57]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX57

[TwitchEmoteY57]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY57

[TwitchEmoteImage57]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID57].png
X=[TwitchEmoteX57]
Y=(55 + [TwitchEmoteY57])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID58]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID58

[TwitchEmoteX58]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX58

[TwitchEmoteY58]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY58

[TwitchEmoteImage58]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID58].png
X=[TwitchEmoteX58]
Y=(55 + [TwitchEmoteY58])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID59]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID59

[TwitchEmoteX59]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX59

[TwitchEmoteY59]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY59

[TwitchEmoteImage59]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID59].png
X=[TwitchEmoteX59]
Y=(55 + [TwitchEmoteY59])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID60]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID60

[TwitchEmoteX60]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX60

[TwitchEmoteY60]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY60

[TwitchEmoteImage60]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID60].png
X=[TwitchEmoteX60]
Y=(55 + [TwitchEmoteY60])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID61]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID61

[TwitchEmoteX61]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX61

[TwitchEmoteY61]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY61

[TwitchEmoteImage61]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID61].png
X=[TwitchEmoteX61]
Y=(55 + [TwitchEmoteY61])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID62]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID62

[TwitchEmoteX62]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX62

[TwitchEmoteY62]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY62

[TwitchEmoteImage62]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID62].png
X=[TwitchEmoteX62]
Y=(55 + [TwitchEmoteY62])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID63]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID63

[TwitchEmoteX63]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX63

[TwitchEmoteY63]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY63

[TwitchEmoteImage63]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID63].png
X=[TwitchEmoteX63]
Y=(55 + [TwitchEmoteY63])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID64]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID64

[TwitchEmoteX64]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX64

[TwitchEmoteY64]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY64

[TwitchEmoteImage64]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID64].png
X=[TwitchEmoteX64]
Y=(55 + [TwitchEmoteY64])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID65]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID65

[TwitchEmoteX65]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX65

[TwitchEmoteY65]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY65

[TwitchEmoteImage65]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID65].png
X=[TwitchEmoteX65]
Y=(55 + [TwitchEmoteY65])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID66]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID66

[TwitchEmoteX66]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX66

[TwitchEmoteY66]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY66

[TwitchEmoteImage66]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID66].png
X=[TwitchEmoteX66]
Y=(55 + [TwitchEmoteY66])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID67]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID67

[TwitchEmoteX67]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX67

[TwitchEmoteY67]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY67

[TwitchEmoteImage67]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID67].png
X=[TwitchEmoteX67]
Y=(55 + [TwitchEmoteY67])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID68]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID68

[TwitchEmoteX68]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX68

[TwitchEmoteY68]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY68

[TwitchEmoteImage68]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID68].png
X=[TwitchEmoteX68]
Y=(55 + [TwitchEmoteY68])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID69]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID69

[TwitchEmoteX69]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX69

[TwitchEmoteY69]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY69

[TwitchEmoteImage69]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID69].png
X=[TwitchEmoteX69]
Y=(55 + [TwitchEmoteY69])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID70]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID70

[TwitchEmoteX70]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX70

[TwitchEmoteY70]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY70

[TwitchEmoteImage70]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID70].png
X=[TwitchEmoteX70]
Y=(55 + [TwitchEmoteY70])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID71]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID71

[TwitchEmoteX71]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX71

[TwitchEmoteY71]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY71

[TwitchEmoteImage71]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID71].png
X=[TwitchEmoteX71]
Y=(55 + [TwitchEmoteY71])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID72]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID72

[TwitchEmoteX72]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX72

[TwitchEmoteY72]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY72

[TwitchEmoteImage72]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID72].png
X=[TwitchEmoteX72]
Y=(55 + [TwitchEmoteY72])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID73]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID73

[TwitchEmoteX73]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX73

[TwitchEmoteY73]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY73

[TwitchEmoteImage73]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID73].png
X=[TwitchEmoteX73]
Y=(55 + [TwitchEmoteY73])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID74]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID74

[TwitchEmoteX74]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX74

[TwitchEmoteY74]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY74

[TwitchEmoteImage74]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID74].png
X=[TwitchEmoteX74]
Y=(55 + [TwitchEmoteY74])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID75]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID75

[TwitchEmoteX75]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX75

[TwitchEmoteY75]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY75

[TwitchEmoteImage75]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID75].png
X=[TwitchEmoteX75]
Y=(55 + [TwitchEmoteY75])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID76]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID76

[TwitchEmoteX76]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX76

[TwitchEmoteY76]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY76

[TwitchEmoteImage76]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID76].png
X=[TwitchEmoteX76]
Y=(55 + [TwitchEmoteY76])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID77]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID77

[TwitchEmoteX77]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX77

[TwitchEmoteY77]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY77

[TwitchEmoteImage77]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID77].png
X=[TwitchEmoteX77]
Y=(55 + [TwitchEmoteY77])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID78]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID78

[TwitchEmoteX78]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX78

[TwitchEmoteY78]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY78

[TwitchEmoteImage78]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID78].png
X=[TwitchEmoteX78]
Y=(55 + [TwitchEmoteY78])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID79]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID79

[TwitchEmoteX79]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX79

[TwitchEmoteY79]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY79

[TwitchEmoteImage79]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID79].png
X=[TwitchEmoteX79]
Y=(55 + [TwitchEmoteY79])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID80]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID80

[TwitchEmoteX80]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX80

[TwitchEmoteY80]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY80

[TwitchEmoteImage80]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID80].png
X=[TwitchEmoteX80]
Y=(55 + [TwitchEmoteY80])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID81]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID81

[TwitchEmoteX81]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX81

[TwitchEmoteY81]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY81

[TwitchEmoteImage81]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID81].png
X=[TwitchEmoteX81]
Y=(55 + [TwitchEmoteY81])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID82]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID82

[TwitchEmoteX82]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX82

[TwitchEmoteY82]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY82

[TwitchEmoteImage82]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID82].png
X=[TwitchEmoteX82]
Y=(55 + [TwitchEmoteY82])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID83]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID83

[TwitchEmoteX83]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX83

[TwitchEmoteY83]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY83

[TwitchEmoteImage83]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID83].png
X=[TwitchEmoteX83]
Y=(55 + [TwitchEmoteY83])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID84]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID84

[TwitchEmoteX84]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX84

[TwitchEmoteY84]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY84

[TwitchEmoteImage84]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID84].png
X=[TwitchEmoteX84]
Y=(55 + [TwitchEmoteY84])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID85]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID85

[TwitchEmoteX85]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX85

[TwitchEmoteY85]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY85

[TwitchEmoteImage85]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID85].png
X=[TwitchEmoteX85]
Y=(55 + [TwitchEmoteY85])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID86]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID86

[TwitchEmoteX86]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX86

[TwitchEmoteY86]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY86

[TwitchEmoteImage86]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID86].png
X=[TwitchEmoteX86]
Y=(55 + [TwitchEmoteY86])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID87]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID87

[TwitchEmoteX87]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX87

[TwitchEmoteY87]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY87

[TwitchEmoteImage87]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID87].png
X=[TwitchEmoteX87]
Y=(55 + [TwitchEmoteY87])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID88]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID88

[TwitchEmoteX88]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX88

[TwitchEmoteY88]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY88

[TwitchEmoteImage88]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID88].png
X=[TwitchEmoteX88]
Y=(55 + [TwitchEmoteY88])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID89]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID89

[TwitchEmoteX89]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX89

[TwitchEmoteY89]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY89

[TwitchEmoteImage89]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID89].png
X=[TwitchEmoteX89]
Y=(55 + [TwitchEmoteY89])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID90]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID90

[TwitchEmoteX90]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX90

[TwitchEmoteY90]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY90

[TwitchEmoteImage90]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID90].png
X=[TwitchEmoteX90]
Y=(55 + [TwitchEmoteY90])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID91]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID91

[TwitchEmoteX91]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX91

[TwitchEmoteY91]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY91

[TwitchEmoteImage91]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID91].png
X=[TwitchEmoteX91]
Y=(55 + [TwitchEmoteY91])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID92]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID92

[TwitchEmoteX92]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX92

[TwitchEmoteY92]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY92

[TwitchEmoteImage92]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID92].png
X=[TwitchEmoteX92]
Y=(55 + [TwitchEmoteY92])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID93]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID93

[TwitchEmoteX93]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX93

[TwitchEmoteY93]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY93

[TwitchEmoteImage93]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID93].png
X=[TwitchEmoteX93]
Y=(55 + [TwitchEmoteY93])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID94]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID94

[TwitchEmoteX94]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX94

[TwitchEmoteY94]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY94

[TwitchEmoteImage94]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID94].png
X=[TwitchEmoteX94]
Y=(55 + [TwitchEmoteY94])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID95]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID95

[TwitchEmoteX95]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX95

[TwitchEmoteY95]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY95

[TwitchEmoteImage95]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID95].png
X=[TwitchEmoteX95]
Y=(55 + [TwitchEmoteY95])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID96]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID96

[TwitchEmoteX96]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX96

[TwitchEmoteY96]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY96

[TwitchEmoteImage96]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID96].png
X=[TwitchEmoteX96]
Y=(55 + [TwitchEmoteY96])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID97]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID97

[TwitchEmoteX97]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX97

[TwitchEmoteY97]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY97

[TwitchEmoteImage97]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID97].png
X=[TwitchEmoteX97]
Y=(55 + [TwitchEmoteY97])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID98]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID98

[TwitchEmoteX98]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX98

[TwitchEmoteY98]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY98

[TwitchEmoteImage98]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID98].png
X=[TwitchEmoteX98]
Y=(55 + [TwitchEmoteY98])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;

[TwitchEmoteID99]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteID99

[TwitchEmoteX99]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteX99

[TwitchEmoteY99]
Measure=Plugin
Plugin=Twitch.dll
DynamicVariables=1
Type=TwitchEmoteY99

[TwitchEmoteImage99]
Meter=Image
ImageName=C:\Emotes\[TwitchEmoteID99].png
X=[TwitchEmoteX99]
Y=(55 + [TwitchEmoteY99])
W=[TwitchEmoteSize]
H=[TwitchEmoteSize]
DynamicVariables=1

;------------------------------------------------;
